%YAML:1.0

#--------------------------------------------------------------------------------------------
# IMU Parameters (fixed).
#--------------------------------------------------------------------------------------------

# IMU data rate
IMU.dps: 142

# Threshold of small angle (<1/2deg)
IMU.nSmallAngle: 0.008726646

# IMU sensor noise
IMU.sigma_g: 1.6968e-02 #8.2739 #1.6968e-04
IMU.sigma_wg: 1.9393e-02 #8.7367 # 1.9393e-05
IMU.sigma_a: 2.0000e-2 #0.0017 #2.0000e-3
IMU.sigma_wa: 3.0000e-2 #0.0057 # 3.0000e-3

# Gravity
IMU.nG: 9.8082

#--------------------------------------------------------------------------------------------
# Camera Parameters (fixed).
#--------------------------------------------------------------------------------------------

# Camera frame rate
Camera.fps: 15

# Is RGB or not 
Camera.RGB: 0 

# Is fisheye or not
Camera.Fisheye: 0

# Camera image resolution
Camera.width: 672
Camera.height: 376

# Camera intrinsics
Camera.fx: 348.522264
Camera.fy: 348.449870
Camera.cx: 344.483596
Camera.cy: 188.808062

Camera.k1: -0.174497
Camera.k2: 0.027127
Camera.p1: -0.000359
Camera.p2: 0.000457

# Camera image noise (1/f)
Camera.sigma_px: 0.00286925715
Camera.sigma_py: 0.00286985327

# Camera extrinsics [B:IMU,C0:cam0]
Camera.T_BC0: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [0.009471441780975032, -0.993908174856504067, 0.109803605332439408, -0.030950056130583600,
           0.998456742062808433, 0.003390918380430374, -0.055431362078334365, -0.077136433704428381,
           0.054721348849528062, 0.110159164965742976, 0.992406435062841652, 0.026512487799308242,
           0.0, 0.0, 0.0, 1.0]

# Timeshift of camera to IMU [s] (t_imu=t_cam+shift)
Camera.nTimeOffset: 0

#--------------------------------------------------------------------------------------------
# Tracker Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Number of features per image 
Tracker.nFeatures: 200

# Max. tracking length
Tracker.nMaxTrackingLength: 10 # 10 # 5

# Min. tracking length
Tracker.nMinTrackingLength: 3

# Min. distance between features
Tracker.nMinDist: 10

# Quality level of features
Tracker.nQualLvl: 0.01

# Size of chess grid
Tracker.nGridSize: 100

# Use histogram equalizer or not
Tracker.EnableEqualizer: 0

# Use Sampson error or not (RANSAC)
Tracker.UseSampson: 1

# Error threshold for inlier (RANSAC)
Tracker.nInlierThrd: 1e-4

#--------------------------------------------------------------------------------------------
# Initialization Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Thresholds for moving detection [rad,m]
INI.nThresholdAngle: 0.005
INI.nThresholdDispl: 0.01

# Use gravity alignment or not
INI.EnableAlignment: 1

# Record the outputs or not
INI.RecordOutputs: 0

#--------------------------------------------------------------------------------------------
# Display Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Size of point
Landmark.nScale: 0.03

# Publishing rate
Landmark.nPubRate: 5
